# USE THE OFFICIAL NODE.JS IMAGE AS THE BASE IMAGE
FROM node:14
# SPECIFIED THE WORKING DIRECTORY
WORKDIR /app
# COPY THE PACKAGES.JSON FILE INTO THE CONTAINER
COPY package.json .
# INSTALLING THE PROJECT DIRECTORY USING NPM
RUN npm install
# COPY THE REST OF THE PROJECT FILE INTO THE CONTAINER 
COPY . .
# SPECIFIED THE COMMAND TO RUN THE PROJECT WHEN THE CONTAINER START
CMD [ "npm", "start" ]